name: Release
on:
  release:
    types:
      - published

jobs:
  smoke-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
        poetry-version: ["1.8.2"]
      fail-fast: false

    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Set Up python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - name: Install dependencies
      run: poetry install --with dev

    - name: Run tests
      env:
        MAG_API_KEY: ${{ secrets.MAG_API_KEY }}
      run: poetry run pytest -vs smoke/test_smoke.py

    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v1


  publish:
    needs: [smoke-test]
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]
        poetry-version: [1.8.2]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build
