name: Release
on:
  release:
    types:
      - published

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
      fail-fast: false

    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Set Up python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v4
      id: setup-rye
      with:
        enable-cache: true
        cache-prefix: ${{ matrix.python-version }}

    - name: Pin python-version ${{ matrix.python-version }}
      run: rye pin ${{ matrix.python-version }}

    - name: Install dependencies
      if: steps.setup-rye.outputs.cache-hit != 'true'
      run: |
        rye sync --no-lock

    - name: Run tests
      env:
        MAG_API_KEY: ${{ secrets.MAG_API_KEY }}
      run: rye run pytest -vs smoke/test_smoke.py

    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v1


  publish:
    # needs: [smoke-test]
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v4
        id: setup-rye
        with:
          enable-cache: true
          cache-prefix: ${{ matrix.python-version }}

      - name: Publish To PyPi
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          rye build
          rye run twine upload dist/* -u __token__ -p $PYPI_TOKEN
