
name: tests

on:
  push:
    branches:
      - master
      - 'releases/**'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12"]
      fail-fast: false

    steps:
    - name: Check out
      uses: actions/checkout@v3


    - name: Set Up python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}


    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry


    - name: Load cached venv
      uses: actions/cache@v3
      with:
        path: .tox
        key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}


    - name: Install tox
      run: |
        pip install tox tox-gh-actions


    - name: Test with tox
      run: tox

    #
    # - name: Upload coverage reports to Codecov with GitHub Action on Python 3.11
    #   uses: codecov/codecov-action@v3
    #   if: ${{ matrix.python-version == '3.11' }}
    
