
name: tests

on:
  push:
    branches:
      - master
      - 'releases/**'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
      fail-fast: false

    steps:
    - name: Check out
      uses: actions/checkout@v3


    - name: Set Up python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}


    - name: Install uv
      uses: astral-sh/setup-uv@v5
      id: setup-uv
      with:
        enable-cache: true

    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Test with tox
      run: uv run tox

    #
    # - name: Upload coverage reports to Codecov with GitHub Action on Python 3.11
    #   uses: codecov/codecov-action@v3
    #   if: ${{ matrix.python-version == '3.11' }}
    
